---
title: "comparing multiple pilots"
output: html_document
---

``` {r libraries}
library(knitr)
library(rmarkdown)
library(purrr)
library(dplyr)
library(tidyr)
library(psqlfun)
library(lme4)
library(MuMIn)
library(ggplot2)
library(xlsx)
library(proxy)
library(pvclust)
library(cluster)
library(lazyeval)
library("stringdist")
```

```{r proximities}

r_pilot_dimensions <- readRDS(paste0(pilot_database_folder, "r_pilot_dimensions.rds"))
r_pilot_attributes <- readRDS(paste0(pilot_database_folder, "r_pilot_attributes.rds"))
r_pilot_evaluation <- readRDS(paste0(pilot_database_folder, "r_pilot_evaluation.rds"))
r_pilot_attributes_pr <- readRDS(paste0(pilot_database_folder, "r_pilot_attributes_pr.rds"))


con_general <- conn2_psql(username = "process", db_host = "172.24.16.194")

wave_db  <- tbl ( con_general, sql('select * from edna.wave') ) %>% select(wave_id = id, code = code)
entity_db  <- tbl ( con_general, sql('select * from edna.entity') ) %>% select(fmid, name, entity_type_id)


dimensions_db <-  tbl(con_general, sql('select * from prd_tv.measures_long')) %>% 
  filter(wave == "3.1", measure != "n") %>% 
  filter(grp_lab == "total") %>%  
  filter (measure_grp == "dimension" & metric == "normalized" )  %>% 
  select(fmid, name, network, genre, wave,measure_grp, metric, measure, value, entity_type_id)

```

```{r collect_tbls} 
dimension_wide <- dimensions_db %>% 
  filter(measure_grp == "dimension") %>% 
  collect(n = Inf) %>% 
  spread(measure, value)


attributes_db <-  tbl(con_general, sql('select * from prd_tv.measures_long')) %>% 
  filter(wave == "3.1", measure != "n") %>% 
  filter(grp_lab == "total") %>%  
  filter(measure_grp == "attributes" & metric %in% c("pctrank", "raw"  ) ) %>% 
  select(fmid, name, network, genre, wave,measure_grp, metric, measure, value, entity_type_id)

attributes_pr <- attributes_db %>% 
  filter(metric == "pctrank") %>% 
  collect(n = Inf)
```


```{r do_proximities}

pilot_dimensions_wide  <- r_pilot_dimensions %>% 
  spread(measure, value) %>% 
  mutate(entity_type_id = -1)

e_dimensions <- bind_rows(pilot_dimensions_wide, dimension_wide )

e_dimensions_vals <- e_dimensions %>% 
  select(adrenaline, edge, gravity, heart, originality, passion, relatability, smarts) 

sim_matrix <- simil(e_dimensions_vals, 
  method = "cosine", by_rows = TRUE, diag = TRUE   ) %>% 
  as.matrix(diag = TRUE) 

e_dimensions <-  e_dimensions %>% 
  mutate(name = ifelse(name =="Vice" & is.na(network), "Vice Network", name))

proximities_df<- cbind(e_dimensions %>% select(name, genre, network, entity_type_id),  sim_matrix)
colnames(proximities_df) <- c("name", "genre", "network", "entity_type_id", e_dimensions %>% select(name) %>% unlist() )

proximities_df_long <- proximities_df %>% 
  gather(to_name, value, -name,-genre, -network, -entity_type_id) %>% 
  left_join(e_dimensions %>% select(to_name = name, to_network = network, to_genre = genre, to_entity_type_id = entity_type_id))

entity_type_codes <- data.frame(to_entity_type_id = c(-1, 1, 2), entity_type = c("pilot", "show", "network"))

proximities_df_long_out <- proximities_df_long %>% 
  filter((network == "truTV" & to_network == "truTV" ) | name == "truTV" | to_name == "truTV") %>% 
  filter(entity_type_id == -1) %>% 
  select(-entity_type_id)  %>% 
  left_join(entity_type_codes) %>% 
  select(name, network, genre, to_name, to_network, to_genre, to_entity_type = entity_type, similarity = value )


write.xlsx(proximities_df_long_out, "All Pilot Proximities.xlsx" ) 

```

```{r rankers_on_attributes}

pilot_attributes_wide  <- r_pilot_attributes_pr %>% 
  mutate(entity_type_id = -1, network = "truTV")

attributes_wide <- attributes_pr %>% 
  filter(entity_type_id == 1) %>% 
  select(name, network, genre, measure, entity_type_id, value) %>% 
  spread(measure, value) 

e_attributes <- bind_rows(pilot_attributes_wide, attributes_wide) %>% 
  gather(measure, value, -name, -wave, -genre, -entity_type_id, -network) %>% 
  left_join(entity_type_codes  %>% rename(entity_type_id = to_entity_type_id) ) %>% 
  filter(network == "truTV") %>% 
  select(name, genre, entity_type, network, attribute = measure, percent_rank = value) %>% 
  mutate(percent_rank = round(percent_rank,1))


write.xlsx(e_attributes, "truTV attribute percent_rank.xlsx" ) 

``` 
