---
title: "Pilot Testing Template"
output: html_document
params:
  pilot_name: "Talk Show The Game Show"
  pilot_genre: "Information"
  wave_year: "2016"
  pilot_network: "TruTV"
  network_type: "Basic Cable"
  nets_to_exclude: c("Univisi贸n", "NBC Universo", "Univisi贸n Deportes", "Telemundo")
---

``` {r libraries}
library(knitr)
library(rmarkdown)
library(purrr)
library(dplyr)
library(tidyr)
library(psqlfun)
library(lme4)
library(MuMIn)
library(ggplot2)
library(xlsx)
library(proxy)
library(pvclust)
library(cluster)
library(lazyeval)
library("stringdist")
```

```{r setup_data}
raw_data_folder <- "raw_data"
pilot_name <- params$pilot_name
processed_data_folder <- paste0("processed_data/", pilot_name)
unlink(processed_data_folder,recursive = TRUE)
dir.create(processed_data_folder)
pilot_network <- params$pilot_network
pilot_network_type <- params$network_type
pilot_genre <- params$pilot_genre
wave_name <- paste0(pilot_name, " ", params$wave_year)

temp_fmid <- data.frame(name = c(pilot_name), fmid = as.character(c(-1) ) )


nets_to_compare <- c()
# nets_to_exclude <- c("Univisi贸n", "NBC Universo", "Univisi贸n Deportes", "Telemundo")

nets_to_exclude <- params$nets_to_exclude


#dimension order
dim_order <- data.frame(dimension = c("adrenaline", "edge", "gravity", "heart", "originality", "passion", "relatability"),
                        order  = c(5, 8,1, 3,4,7, 2), stringsAsFactors = FALSE ) %>% arrange(order)
use_adjustments <- TRUE

model_list1.1 <-readRDS("/home/aaron/Prep TV 1.2/data1.2/model_list1.1.rds")

file.path1 <- paste0(raw_data_folder, "/", pilot_name, ".xlsx")

pilot_database_folder <- ("~/pilot_database/")

```

```{r adjustments}

#default is to not adjust
att_adj <- 1
eval_adj <- 1

#these adjustments are based on how pilots generally performed in test versus in real life (i.e., wave data)
if(use_adjustments){
att_adj <- .64
eval_adj <- .89}

```


```{r get_pilot_data}

pilot_data <- read.xlsx(file.path1,1, stringsAsFactors = FALSE) %>% 
  mutate(name= pilot_name, network = pilot_network) 

write.xlsx(data.frame(pilot_data),paste0(processed_data_folder,"/", pilot_name, " unadjusted_attributes.xlsx") )
```

``` {r load_needed_tables}

con_general <- conn2_psql(username = "process", db_host = "172.24.16.194")

wave_db  <- tbl ( con_general, sql('select * from edna.wave') ) %>% select(wave_id = id, code = code)
entity_db  <- tbl ( con_general, sql('select * from edna.entity') ) %>% select(fmid, name, entity_type_id)

dimensions_pnorm_db <-  tbl(con_general, sql('select * from prd_tv.measures_long')) %>% 
  filter(wave == "3.1", measure != "n") %>% 
  filter(grp_lab == "total") %>%  
  filter (measure_grp == "dimension" & metric == "raw" )  %>% 
  select(fmid, name, network_type, genre, wave,measure_grp, metric, measure, value, entity_type_id)

dimensions_db <-  tbl(con_general, sql('select * from prd_tv.measures_long')) %>% 
  filter(wave == "3.1", measure != "n") %>% 
  filter(grp_lab == "total") %>%  
  filter (measure_grp == "dimension" & metric == "normalized" )  %>% 
  select(fmid, name, network, genre, wave,measure_grp, metric, measure, value, entity_type_id)

evaluations_db <-  tbl(con_general, sql('select * from prd_tv.re_evaluation')) %>% 
  left_join(entity_db) %>% 
  left_join(wave_db %>% rename(wave = code)) %>% 
  filter(wave == "3.1") %>%
  group_by(fmid, name) %>% 
  summarize(evaluation = mean(evaluation))
  
attributes_db <-  tbl(con_general, sql('select * from prd_tv.measures_long')) %>% 
  filter(wave == "3.1", measure != "n") %>% 
  filter(grp_lab == "total") %>%  
  filter(measure_grp == "attributes" & metric %in% c("pctrank", "raw"  ) ) %>% 
  select(fmid, name, network, genre, wave,measure_grp, metric, measure, value, entity_type_id)
```


```{r collect_tbls} 
dimension_wide <- dimensions_db %>% 
  filter(measure_grp == "dimension") %>% 
  collect(n = Inf) %>% 
  spread(measure, value)

dimension_pnorm_wide <- dimensions_pnorm_db %>% 
  filter(measure_grp == "dimension") %>% 
  collect(n = Inf) %>% 
  mutate(value = round(value,2)) %>% 
  spread(measure, value)

evaluations <- evaluations_db %>% 
  select(fmid, name, evaluation) %>% collect(n = Inf)

attributes_col <- attributes_db %>% 
  filter(metric == "raw") %>% 
  collect(n = Inf)

```


```{r functions_for_testing}
# get attribute nmames to conform to what we have in our model list

model_vars <- all.vars(formula(model_list1.1[[1]]))
model_vars <- model_vars[2:length(model_vars)]

replace_closest <- function(df, model_vars, colstr, maxDist = 4)
{
  
  df<-ungroup(df)
  
  convert_vars <- df %>% 
    count_(colstr) %>%
    select_(colstr) %>% 
    mutate_(.dots = setNames(list(interp(~x[amatch(a, x, maxDist =m)], a = as.name(colstr), x= model_vars,m = maxDist )), "closest"))

  convert_vars <- df %>% 
    count_(colstr) %>%
    select_(colstr) %>% 
    mutate_(closest= interp(~model_vars[amatch(colstr, model_vars, maxDist =maxDist)], colstr=as.name(colstr)))
  
  df <- df %>% 
    left_join(convert_vars) %>% 
    mutate_(.dots  = setNames("closest",colstr) ) %>% 
    select(-closest)
  
  return(df)
}


get_coefficients <- function(m ){
  return(m$coefficients)
}


mutate_fn <- function(d_in, op_ls,var_vec){
  
  d_out = d_in %>%
    mutate_(.dots = setNames(op_ls,var_vec))
}
```


```{r calculate_pilot_values}

pilot_evaluation <- pilot_data %>% 
  filter(measure_grp == "evaluation") %>% 
  select(name, network, attribute, value = total) %>% 
  separate(attribute, convert = TRUE,  into = c("measure", "eval_weight") ) %>% 
  group_by(name,network, measure) %>% 
  summarize(value = sum(eval_weight*value)) %>% 
  mutate(measure = "evaluation", wave = wave_name) %>% 
  mutate(value = (eval_adj * value))
  
pilot_attributes <- pilot_data %>% 
  filter(measure_grp == "attribute") %>% 
  select(name, network, attribute, value = total) %>% 
  mutate(value = att_adj *value)

pilot_attributes<- replace_closest(pilot_attributes, model_vars, "attribute")

pilot_attributes_wide <- pilot_attributes %>%
  spread(attribute, value)

predictions <- lapply(model_list1.1, function(x) predict(x,  pilot_attributes_wide )) %>% data.frame()

pilot_dimensions <- cbind(pilot_attributes_wide %>% select(name, network), predictions) %>% 
  gather(measure, value, -network, -name) %>% 
  mutate(wave = wave_name)

pilot_dimensions_pnorm <- pilot_dimensions %>% 
  mutate(value = round(pnorm(value),4) ) %>% 
  mutate(wave = wave_name)

dim_contribution <- function (attribute_df) {
coefficient_mat <-  lapply(model_list1.1, function(x) get_coefficients(x)) %>% data.frame() %>% 
  data.frame(attribute = rownames(.), .) %>% 
  gather(dimension, weight, -attribute) %>% 
  mutate(attribute = as.character(attribute))

intercept_val <- attribute_df[1,] %>% 
  mutate(attribute="(Intercept)", value = 1)

attribute_df <-rbind(intercept_val, attribute_df )

dim_contribute <- coefficient_mat %>% 
  left_join(attribute_df) %>% 
  mutate(contribution = weight*value) %>% 
  select(attribute, dimension, name, network, contribution) %>% 
  spread(dimension, contribution)

return(dim_contribute)
}

```


```{r do_dim_contribution}

dim_contribution_df <- pilot_attributes %>% 
  split(., pilot_attributes$name) %>% 
  map(~dim_contribution(.) )
```

```{r do_proximities}

pilot_dimensions_wide  <- pilot_dimensions %>% 
  spread(measure, value) %>% 
  mutate(genre = pilot_genre,  entity_type_id = -1)

e_dimensions <- bind_rows(pilot_dimensions_wide, dimension_wide )

e_dimensions_vals <- e_dimensions %>% 
  select(adrenaline, edge, gravity, heart, originality, passion, relatability, smarts) 

sim_matrix <- simil(e_dimensions_vals, 
  method = "cosine", by_rows = TRUE, diag = TRUE   ) %>% 
  as.matrix(diag = TRUE) 

e_dimensions <-  e_dimensions %>% 
  mutate(name = ifelse(name =="Vice" & is.na(network), "Vice Network", name))

proximities_df<- cbind(e_dimensions %>% select(name, genre, network),  sim_matrix)
colnames(proximities_df) <- c("name", "genre", "network", e_dimensions %>% select(name) %>% unlist() )

proximities_df_out <- proximities_df %>% 
select_(.dots = c("name",  "genre" , "network", paste0("`", pilot_name, "`") ) )


write.xlsx(proximities_df_out, paste0(processed_data_folder,"/", pilot_name," Proximities.xlsx" ) )

```

```{r write_dimensions_to_file}
####Write Dimensions and attributes to file
pilot_dimensions_wide_pnorm  <- pilot_dimensions_pnorm %>% 
  mutate(value = round(value*100,2) )%>% 
  spread(measure, value) %>% 
  mutate(genre = pilot_genre,  entity_type_id = 1)

e_dimensions <- bind_rows(pilot_dimensions_wide_pnorm, dimension_pnorm_wide )

op_ls <- list(interp(~f(-var1), .values = list(f = as.name("rank"),
                                              var1 = as.name(pilot_name)) ) )
var_vec <- c("rk")

most_proximate_shows <- proximities_df_out %>%
  filter( genre == pilot_genre)  %>%
  mutate(entity_type = ifelse(is.na(network), "network", "show")) %>%
  group_by(entity_type) %>%
  mutate_fn(op_ls, var_vec) %>%
  arrange((rk)) %>%
  filter(rk < 30)

pilot_attributes_mod <- pilot_attributes %>% 
  rename(measure = attribute) %>% 
  mutate(value  = value * 100, 
         genre = pilot_genre, 
         entity_type_id = 1,
         measure_grp = "attributes") 

all_attributes <-  bind_rows(pilot_attributes_mod, 
                            attributes_col) %>% 
   group_by(entity_type_id, measure) %>% 
   mutate(prk = round(100*percent_rank(value), 2) ) %>% 
   ungroup() %>%
   mutate(name = ifelse(name == "Vice" & is.na(network), "ViceNetwork", name) ) %>% 
   select(name, measure, prk) %>% 
   spread(measure, prk)

dimension_table <- most_proximate_shows %>% select(name) %>% 
  left_join(e_dimensions, by = c("name")) %>% ungroup() %>% 
  arrange(desc(entity_type)) %>% 
  select(name, Gravity = gravity, Relatability = relatability, Heart = heart, Originality = originality, Adrenaline= adrenaline, Smarts = smarts, Passion = passion, Edge = edge) 
  

kable(dimension_table)
write.xlsx(dimension_table, paste0(processed_data_folder,"/", pilot_name, "Dimensions.xlsx") )

kable(most_proximate_shows)
write.xlsx(data.frame(most_proximate_shows),  paste0(processed_data_folder,"/", pilot_name," Closest Proximities.xlsx")  )
```

```{r write_all_proximities_to_file}
####Write Dimensions and attributes to file

proximate_shows <- proximities_df_out %>%
  mutate(entity_type = ifelse(is.na(network), "network", "show")) 

write.xlsx(proximate_shows,  paste0(processed_data_folder,"/", pilot_name," All Proximities.xlsx")  )
```

```{r write_evals_to_file}
all_evals <-bind_rows(pilot_evaluation %>% rename(evaluation = value), evaluations)

evaluations_table <- most_proximate_shows %>% select(name) %>% 
  left_join(all_evals, by = c("name")) %>% ungroup() %>% 
  select(name, evaluation)

kable(evaluations_table)
write.xlsx(evaluations_table,  paste0(processed_data_folder,"/", pilot_name," evaluations.xlsx") )

```

```{r write_attributes_to_file}

attribute_table <- most_proximate_shows %>% select(name, rk) %>% 
  left_join(all_attributes, by = c("name")) %>% ungroup() %>% 
  filter(entity_type == "show", rk < 11) %>% 
  ungroup() %>% 
  select(-entity_type) %>% 
  gather(attribute, value, -name, -rk) %>% 
  spread(attribute, value) %>% 
  arrange(rk)

kable(attribute_table)
write.xlsx(attribute_table,  paste0(processed_data_folder,"/", pilot_name," attributes percent_rank.xlsx") )

```

```{r write_dimension_contributions_to_file}

###dimension contribution

my_write.xlsx <- function(df, wb_name, sN) {
  
  if(!file.exists(wb_name)) {write.xlsx(df, wb_name, sheetName = sN, row.names = FALSE)}
  else{write.xlsx(df, wb_name, append = TRUE, sheetName = sN, row.names = FALSE)
    
  }
  
}

names(dim_contribution_df) %>% 
  map(~my_write.xlsx(dim_contribution_df[[.]], paste0(processed_data_folder,"/", pilot_name, "dimension_contributions.xlsx"), . ))


kable(dim_contribution_df)


```

```{r update_rds_file}
append_rds_data <- function(file_name, df_to_append){
  df <- readRDS(file_name)
  df.new <- rbind(df, df_to_append)
  saveRDS(df.new, file_name)
}

remove_rds_data <- function(file_name, name, wave){
  df <- readRDS(file_name)
  pilot_identifier_df <- data.frame(name = name, wave= wave)
  df.new <-df %>%  anti_join(pilot_identifier_df)
  saveRDS(df.new, file_name)
}

unique_append_rds <- function(file_name, df_to_append, name, wave){
remove_rds_data(file_name, name, wave)
append_rds_data(file_name, df_to_append)
}

```


```{r save_pilot_raw_dimensions_results}
pilot_dimensions_out <- pilot_dimensions %>% 
  mutate(genre = pilot_genre)
pilot_attributes_out <- pilot_attributes %>% 
  mutate(wave = wave_name, genre = pilot_genre)
pilot_attributes_percent_rank_out <- all_attributes %>% 
  mutate(wave = wave_name, genre = pilot_genre) %>% 
  filter(name == pilot_name)
pilot_evaluation_out <- pilot_evaluation %>% 
  mutate(genre = pilot_genre)

# saveRDS(pilot_dimensions_out, paste0(pilot_database_folder, "r_pilot_dimensions.rds") )
# saveRDS(pilot_attributes_out, paste0(pilot_database_folder, "r_pilot_attributes.rds") )
# saveRDS(pilot_evaluation_out, paste0(pilot_database_folder, "r_pilot_evaluation.rds") )
# saveRDS(pilot_attributes_percent_rank_out, paste0(pilot_database_folder, "r_pilot_attributes_pr.rds") )

unique_append_rds(paste0(pilot_database_folder, "r_pilot_dimensions.rds"), pilot_dimensions_out, pilot_name, wave_name)
unique_append_rds(paste0(pilot_database_folder, "r_pilot_attributes.rds"), pilot_attributes_out, pilot_name, wave_name)
unique_append_rds(paste0(pilot_database_folder, "r_pilot_evaluation.rds"), pilot_evaluation_out, pilot_name, wave_name)
unique_append_rds(paste0(pilot_database_folder, "r_pilot_attributes_pr.rds"), pilot_attributes_percent_rank_out, pilot_name, wave_name)


# y1 <- readRDS(paste0(pilot_database_folder, "r_pilot_dimensions.rds"))
# y2 <- readRDS(paste0(pilot_database_folder, "r_pilot_attributes.rds"))
# y3 <- readRDS(paste0(pilot_database_folder, "r_pilot_evaluation.rds"))



```

