---
title: "pilot_testing_list"
output: html_document
---

```{r libraries}

library(knitr)
library(rmarkdown)

```

```{r pilot_tests}

rmarkdown::render("Pilot Analysis.Rmd", params = list(pilot_name = "Small Victories", pilot_genre = "Comedy", wave_year = "2016"))
rmarkdown::render("Pilot Analysis.Rmd", params = list(pilot_name = "Talk Show The Game Show", pilot_genre = "Information",wave_year = "2016"))
rmarkdown::render("Pilot Analysis.Rmd", params = list(pilot_name = "Jon Glaser 101", pilot_genre = "Comedy",  wave_year = "2016"))
rmarkdown::render("Pilot Analysis.Rmd", params = list(pilot_name = "Jon Glaser 102", pilot_genre = "Comedy",  wave_year = "2016"))
rmarkdown::render("Pilot Analysis.Rmd", params = list(pilot_name = "Upscale", pilot_genre = "Unscripted",  wave_year = "2016"))
rmarkdown::render("Pilot Analysis.Rmd", params = list(pilot_name = "Those who cant 201", pilot_genre = "Comedy",  wave_year = "2016"))
rmarkdown::render("Pilot Analysis.Rmd", params = list(pilot_name = "Those who cant 203", pilot_genre = "Comedy",  wave_year = "2016"))
rmarkdown::render("Pilot Analysis.Rmd", params = list(pilot_name = "Im Sorry", pilot_genre = "Comedy",  wave_year = "2016"))


rmarkdown::render("Pilot Analysis.Rmd", params = list(pilot_name = "Claws", pilot_genre = "Drama",  wave_year = "2016", pilot_network = "TNT" ))

```

